# Generated by Django 3.2.11 on 2024-08-09 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0003_auto_20240807_2324'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='descuento',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
