# Generated by Django 3.2.11 on 2024-08-09 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0004_book_descuento'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='descuento',
            new_name='discount',
        ),
        migrations.AddField(
            model_name='book',
            name='editorial',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='book',
            name='state',
            field=models.CharField(choices=[('New', 'New'), ('Used', 'Used'), ('Collectible', 'Collectible'), ('Refurbished', 'Refurbished'), ('Unspecified', 'Unspecified')], default='Nuevo', max_length=200),
        ),
    ]
