# Generated by Django 3.2.11 on 2024-08-11 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0006_auto_20240811_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image2',
            field=models.ImageField(blank=True, upload_to='images/books_img/'),
        ),
        migrations.AlterField(
            model_name='book',
            name='image3',
            field=models.ImageField(blank=True, upload_to='images/books_img/'),
        ),
        migrations.AlterField(
            model_name='book',
            name='image4',
            field=models.ImageField(blank=True, upload_to='images/books_img/'),
        ),
        migrations.AlterField(
            model_name='book',
            name='slug',
            field=models.SlugField(max_length=60),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=150),
        ),
    ]
