# Generated by Django 3.2.11 on 2024-08-11 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0009_auto_20240811_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image_google_api',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/books_img/'),
        ),
    ]
