# Generated by Django 3.2.11 on 2024-08-14 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '__first__'),
        ('bookstore', '0010_auto_20240811_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='ihave',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='book',
            name='iloveyou',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='book',
            name='iwish',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='BookTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=60)),
                ('image', models.ImageField(blank=True, upload_to='images/books_img/')),
                ('image2', models.ImageField(blank=True, upload_to='images/books_img/')),
                ('image3', models.ImageField(blank=True, upload_to='images/books_img/')),
                ('image4', models.ImageField(blank=True, upload_to='images/books_img/')),
                ('image_google_api', models.CharField(blank=True, max_length=200)),
                ('author', models.CharField(blank=True, max_length=200)),
                ('discount', models.CharField(blank=True, max_length=200)),
                ('editorial', models.CharField(blank=True, max_length=200)),
                ('isbn', models.CharField(blank=True, max_length=200)),
                ('format', models.CharField(blank=True, max_length=200)),
                ('year', models.CharField(blank=True, max_length=200)),
                ('number_pages', models.CharField(blank=True, max_length=200)),
                ('binding', models.CharField(blank=True, max_length=200)),
                ('dimensions', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True, max_length=3000)),
                ('stocks', models.IntegerField()),
                ('stocks_available', models.BooleanField(default=True)),
                ('modified_on', models.DateTimeField(auto_now_add=True)),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.category')),
            ],
        ),
    ]
