# Generated by Django 3.2.11 on 2024-08-15 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0011_auto_20240814_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='bookstore.booktemplate'),
        ),
    ]
