# Generated by Django 3.2.11 on 2024-08-15 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0012_book_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booktemplate',
            name='category',
        ),
        migrations.AddField(
            model_name='booktemplate',
            name='categories_list',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
