# Generated by Django 3.2.11 on 2024-08-15 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0013_auto_20240815_1425'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booktemplate',
            name='stocks',
        ),
    ]
