# Generated by Django 3.2.11 on 2024-08-15 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0014_remove_booktemplate_stocks'),
    ]

    operations = [
        migrations.AddField(
            model_name='booktemplate',
            name='origen',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
