# Generated by Django 3.2.11 on 2024-08-16 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0015_booktemplate_origen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booktemplate',
            old_name='editorial',
            new_name='publisher',
        ),
    ]
