# Generated by Django 3.2.11 on 2024-08-16 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0016_rename_editorial_booktemplate_publisher'),
    ]

    operations = [
        migrations.AddField(
            model_name='booktemplate',
            name='published_date',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
