# Generated by Django 3.2.11 on 2024-08-16 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0017_booktemplate_published_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='booktemplate',
            name='language',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
